/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/defaults": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Defaults */
        get: operations["defaults_api_defaults_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/intake/questionnaire": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Questionnaire */
        get: operations["questionnaire_api_intake_questionnaire_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/intake/score": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Score */
        post: operations["score_api_intake_score_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/universe": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Funds */
        get: operations["list_funds_api_universe_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/universe/frontier": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Universe Frontier */
        post: operations["universe_frontier_api_universe_frontier_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/universe/{isin}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Fund Detail */
        get: operations["fund_detail_api_universe__isin__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/portfolio": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Portfolio */
        post: operations["portfolio_api_portfolio_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/backtest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Backtest */
        post: operations["backtest_api_backtest_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/frontier": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Frontier */
        post: operations["frontier_api_frontier_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/textbook": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Textbook Portfolio */
        post: operations["textbook_portfolio_api_textbook_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/menu": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Menu */
        get: operations["get_menu_api_menu_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/menu/order": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Order */
        post: operations["order_api_menu_order_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** BacktestRequest */
        BacktestRequest: {
            profile: components["schemas"]["InvestorProfile"];
            /** Weights */
            weights?: {
                [key: string]: number;
            } | null;
            /**
             * @default {
             *       "expected_return_model": "capm_multi_asset",
             *       "strategy": "target_vol",
             *       "estimation_window_years": 5,
             *       "vol_range": [
             *         0.02,
             *         0.2
             *       ],
             *       "drawdown_thresholds": [
             *         0.3,
             *         0.4,
             *         0.5
             *       ],
             *       "mc_paths": 10000,
             *       "seed": 42
             *     }
             */
            settings?: components["schemas"]["EngineSettings"];
            /**
             * @default {
             *       "mode": "static",
             *       "rebalance": {
             *         "frequency": "quarterly",
             *         "threshold": 0.05,
             *         "type": "none"
             *       },
             *       "transaction_cost_bps": 10,
             *       "benchmark": "auto"
             *     }
             */
            backtest?: components["schemas"]["BacktestSettings"];
        };
        /** BacktestResult */
        BacktestResult: {
            series: components["schemas"]["BacktestSeries"];
            /** Metrics */
            metrics: {
                [key: string]: {
                    [key: string]: number | null;
                };
            };
            /** Weights */
            weights: {
                [key: string]: number;
            };
            /**
             * Proxied Periods
             * @default []
             */
            proxied_periods?: components["schemas"]["ProxiedPeriod"][];
            /**
             * Rebalance Dates
             * @default []
             */
            rebalance_dates?: string[];
            /**
             * Warnings
             * @default []
             */
            warnings?: string[];
            /**
             * Trace
             * @default []
             */
            trace?: components["schemas"]["StepResult"][];
            /**
             * References
             * @default []
             */
            references?: components["schemas"]["ReferenceResult"][];
        };
        /** BacktestSeries */
        BacktestSeries: {
            /** Dates */
            dates: string[];
            /** Portfolio */
            portfolio: number[];
            /** Benchmark */
            benchmark: number[];
            /** Drawdown */
            drawdown: number[];
            /** Rolling Vol */
            rolling_vol: (number | null)[];
            /** Rolling Sharpe */
            rolling_sharpe: (number | null)[];
        };
        /** BacktestSettings */
        BacktestSettings: {
            /**
             * Mode
             * @default static
             * @enum {string}
             */
            mode?: "static" | "walk_forward";
            /** Start */
            start?: string | null;
            /** End */
            end?: string | null;
            /**
             * @default {
             *       "type": "none",
             *       "frequency": "quarterly",
             *       "threshold": 0.05
             *     }
             */
            rebalance?: components["schemas"]["RebalanceSettings"];
            /**
             * Transaction Cost Bps
             * @default 10
             */
            transaction_cost_bps?: number;
            /**
             * Benchmark
             * @default auto
             */
            benchmark?: "auto" | {
                [key: string]: number;
            };
        };
        /** Defaults */
        Defaults: {
            /** Vol Range */
            vol_range: [
                number,
                number
            ];
            /** Estimation Window Years */
            estimation_window_years: number;
            /** Markets */
            markets: {
                [key: string]: components["schemas"]["MarketDefault"];
            };
            /** Anchors */
            anchors: {
                [key: string]: {
                    [key: string]: string;
                };
            };
            /** Crypto Min Risk Level */
            crypto_min_risk_level: number;
            /** Crypto Default Cap */
            crypto_default_cap: number;
            /** Crypto Hard Cap */
            crypto_hard_cap: number;
            /** Drawdown Thresholds */
            drawdown_thresholds: number[];
            /** Mc Paths */
            mc_paths: number;
            /** Stress Events */
            stress_events: components["schemas"]["StressEvent"][];
            /** Backtest Years */
            backtest_years: number;
            /** Transaction Cost Bps */
            transaction_cost_bps: number;
            /** Mismatch Gap */
            mismatch_gap: number;
        };
        /** Downside */
        Downside: {
            /** Drawdown Probs */
            drawdown_probs: components["schemas"]["ProbabilityPoint"][];
            /** Annual Loss Probs */
            annual_loss_probs: components["schemas"]["ProbabilityPoint"][];
            /** P Below Invested */
            p_below_invested: number;
            /** Fan */
            fan: components["schemas"]["FanPoint"][];
            /**
             * Fan Money
             * @default []
             */
            fan_money?: components["schemas"]["MoneyFanPoint"][];
            /** P Below Paid In */
            p_below_paid_in?: number | null;
            /** Stress */
            stress: components["schemas"]["StressResult"][];
            normal_comparison: components["schemas"]["NormalComparison"];
            /**
             * Var Monthly
             * @default []
             */
            var_monthly?: components["schemas"]["VarPoint"][];
            /**
             * Var Months
             * @default 0
             */
            var_months?: number;
        };
        /** EngineSettings */
        EngineSettings: {
            /**
             * Expected Return Model
             * @default capm_multi_asset
             * @enum {string}
             */
            expected_return_model?: "capm_equity" | "capm_multi_asset";
            /**
             * Strategy
             * @default target_vol
             * @enum {string}
             */
            strategy?: "target_vol" | "min_variance" | "max_sharpe" | "risk_parity" | "hrp";
            /**
             * Estimation Window Years
             * @default 5
             */
            estimation_window_years?: number;
            /** Market Premium */
            market_premium?: number | null;
            /**
             * Vol Range
             * @default [
             *       0.02,
             *       0.2
             *     ]
             */
            vol_range?: [
                number,
                number
            ];
            /** Drawdown Thresholds */
            drawdown_thresholds?: number[];
            /**
             * Mc Paths
             * @default 10000
             */
            mc_paths?: number;
            /**
             * Seed
             * @default 42
             */
            seed?: number | null;
        };
        /** FanPoint */
        FanPoint: {
            /** Year */
            year: number;
            /** P5 */
            p5: number;
            /** P25 */
            p25: number;
            /** P50 */
            p50: number;
            /** P75 */
            p75: number;
            /** P95 */
            p95: number;
        };
        /** Frontier */
        Frontier: {
            /** Model Curve */
            model_curve: components["schemas"]["FrontierPoint"][];
            /** Capital Market Line */
            capital_market_line: components["schemas"]["FrontierPoint"][];
            /** Markers */
            markers: components["schemas"]["FrontierMarker"][];
            /** Rf */
            rf: number;
            /**
             * Warnings
             * @default []
             */
            warnings?: string[];
            /**
             * Trace
             * @default []
             */
            trace?: components["schemas"]["StepResult"][];
        };
        /** FrontierMarker */
        FrontierMarker: {
            /** Key */
            key: string;
            /** Label */
            label: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "portfolio" | "reference" | "strategy" | "fund";
            model: components["schemas"]["FrontierPoint"];
        };
        /** FrontierPoint */
        FrontierPoint: {
            /** Volatility */
            volatility: number;
            /** Expected Return */
            expected_return: number;
            /** Sharpe */
            sharpe: number | null;
        };
        /** FrontierRequest */
        FrontierRequest: {
            profile: components["schemas"]["InvestorProfile"];
            /**
             * @default {
             *       "expected_return_model": "capm_multi_asset",
             *       "strategy": "target_vol",
             *       "estimation_window_years": 5,
             *       "vol_range": [
             *         0.02,
             *         0.2
             *       ],
             *       "drawdown_thresholds": [
             *         0.3,
             *         0.4,
             *         0.5
             *       ],
             *       "mc_paths": 10000,
             *       "seed": 42
             *     }
             */
            settings?: components["schemas"]["EngineSettings"];
            /**
             * Points
             * @default 20
             */
            points?: number;
        };
        /** FundDetail */
        FundDetail: {
            fund: components["schemas"]["FundSummary"];
            /** Listings */
            listings: components["schemas"]["ListingOut"][];
            /** History */
            history: components["schemas"]["PricePoint"][];
        };
        /** FundSummary */
        FundSummary: {
            /** Isin */
            isin: string;
            /** Name */
            name: string;
            /** Issuer */
            issuer: string | null;
            /** Asset Class */
            asset_class: string;
            /** Sub Class */
            sub_class: string | null;
            /** Region */
            region: string | null;
            /** Sector */
            sector: string | null;
            /** Esg */
            esg: boolean;
            /** Ter */
            ter: number | null;
            /** Domicile */
            domicile: string | null;
            /** Ucits */
            ucits: boolean;
            /** Wrapper */
            wrapper: string;
            /** Distribution */
            distribution: string | null;
            /** Hedged To */
            hedged_to: string | null;
            /** Duration */
            duration: number | null;
            /** Index Name */
            index_name: string | null;
            /** Inception Date */
            inception_date: string | null;
            /** Has Proxy */
            has_proxy: boolean;
            /** Tickers */
            tickers: string[];
        };
        /** GrowthPoint */
        GrowthPoint: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Value */
            value: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Health */
        Health: {
            /** Status */
            status: string;
            /** Data Loaded */
            data_loaded: boolean;
            /** Last Ingest */
            last_ingest: string | null;
            /** N Funds */
            n_funds: number;
        };
        /** Holding */
        Holding: {
            /** Isin */
            isin: string;
            /** Ticker */
            ticker: string;
            /** Exchange */
            exchange: string;
            /** Name */
            name: string;
            /** Weight */
            weight: number;
            /** Asset Class */
            asset_class: string;
            /** Sub Class */
            sub_class: string | null;
            /** Region */
            region: string | null;
            /** Ter */
            ter: number | null;
            /** Beta */
            beta: number;
            /** Expected Return */
            expected_return: number;
            /** Risk Contribution */
            risk_contribution: number;
            /** Proxied */
            proxied: boolean;
            /** Fund Size Eur */
            fund_size_eur?: number | null;
            /** Daily Value Eur */
            daily_value_eur?: number | null;
        };
        /** IntakeAnswers */
        IntakeAnswers: {
            /** Answers */
            answers: {
                [key: string]: string | number;
            };
        };
        /** IntakeScore */
        IntakeScore: {
            /** Capacity */
            capacity: number;
            /** Tolerance */
            tolerance: number;
            /** Suggested Risk Level */
            suggested_risk_level: number;
            /**
             * Limiting Factor
             * @enum {string}
             */
            limiting_factor: "capacity" | "tolerance" | "none";
            /** Mismatch */
            mismatch: boolean;
            /** Explanation */
            explanation: string;
            /** Horizon Years */
            horizon_years: number;
        };
        /** InvestorProfile */
        InvestorProfile: {
            /** Risk Level */
            risk_level: number;
            /** Horizon Years */
            horizon_years: number;
            /**
             * Base Currency
             * @enum {string}
             */
            base_currency: "EUR" | "USD";
            /**
             * @default {
             *       "hedge_bonds": true,
             *       "regions_include": [],
             *       "regions_exclude": [],
             *       "sector_tilts": {},
             *       "sectors_exclude": [],
             *       "esg_only": false,
             *       "max_etfs": 10,
             *       "min_position": 0.03,
             *       "max_position": 0.4,
             *       "distribution": "any",
             *       "crypto_max": 0,
             *       "etfs_only": false
             *     }
             */
            preferences?: components["schemas"]["Preferences"];
            /**
             * Initial Amount
             * @default 0
             */
            initial_amount?: number;
            /**
             * Monthly Amount
             * @default 0
             */
            monthly_amount?: number;
        };
        /** ListingOut */
        ListingOut: {
            /** Ticker */
            ticker: string;
            /** Exchange */
            exchange: string;
            /** Currency */
            currency: string;
            /** Is Primary */
            is_primary: boolean;
        };
        /** MarketDefault */
        MarketDefault: {
            /** Weights */
            weights: {
                [key: string]: number;
            };
            /** Premium */
            premium: number;
        };
        /** Menu */
        Menu: {
            /** Profiles */
            profiles: components["schemas"]["MenuProfile"][];
            /** Items */
            items: components["schemas"]["MenuItem"][];
            /** Horizon Years */
            horizon_years: number;
            /** Min Fund Size Eur */
            min_fund_size_eur: number;
            /** Data As Of */
            data_as_of: string | null;
        };
        /** MenuItem */
        MenuItem: {
            /**
             * Base
             * @enum {string}
             */
            base: "coffee" | "matcha";
            /** Profile Id */
            profile_id: number;
            /** Holdings */
            holdings: components["schemas"]["Holding"][];
            summary: components["schemas"]["PortfolioSummary"];
            /** Var Monthly */
            var_monthly: components["schemas"]["VarPoint"][];
            /** Var Months */
            var_months: number;
            /** P Below Invested */
            p_below_invested: number;
            /** Outcome */
            outcome: {
                [key: string]: number;
            };
            /** Drawdown Probs */
            drawdown_probs: components["schemas"]["ProbabilityPoint"][];
            /** Performance */
            performance: components["schemas"]["Performance"][];
            /** Growth */
            growth: components["schemas"]["GrowthPoint"][];
            /**
             * Warnings
             * @default []
             */
            warnings?: string[];
        };
        /** MenuProfile */
        MenuProfile: {
            /** Id */
            id: number;
            /** Key */
            key: string;
            /** Target Volatility */
            target_volatility: number;
            /** Score Min */
            score_min: number;
            /** Score Max */
            score_max: number;
        };
        /**
         * MoneyFanPoint
         * @description Percentiles of the money value at the end of a year, for the investor's own amounts. paid_in = cumulative deposits.
         */
        MoneyFanPoint: {
            /** Year */
            year: number;
            /** Paid In */
            paid_in: number;
            /** P5 */
            p5: number;
            /** P25 */
            p25: number;
            /** P50 */
            p50: number;
            /** P75 */
            p75: number;
            /** P95 */
            p95: number;
        };
        /** NormalComparison */
        NormalComparison: {
            /** Drawdown Probs */
            drawdown_probs: components["schemas"]["ProbabilityPoint"][];
            /** Annual Loss Probs */
            annual_loss_probs: components["schemas"]["ProbabilityPoint"][];
        };
        /** OrderRequest */
        OrderRequest: {
            /**
             * Base
             * @enum {string}
             */
            base: "coffee" | "matcha";
            /** Profile Id */
            profile_id: number;
            /**
             * Horizon Years
             * @default 10
             */
            horizon_years?: number;
            /**
             * Initial Amount
             * @default 0
             */
            initial_amount?: number;
            /**
             * Monthly Amount
             * @default 0
             */
            monthly_amount?: number;
        };
        /** Performance */
        Performance: {
            /** Years */
            years: number;
            /**
             * Start
             * Format: date
             */
            start: string;
            /**
             * End
             * Format: date
             */
            end: string;
            /** Total Return */
            total_return: number;
            /** Annual Return */
            annual_return: number;
            /** Volatility */
            volatility: number;
            /** Max Drawdown */
            max_drawdown: number;
            /** Worst Month */
            worst_month: number;
        };
        /** PortfolioRequest */
        PortfolioRequest: {
            profile: components["schemas"]["InvestorProfile"];
            /**
             * @default {
             *       "expected_return_model": "capm_multi_asset",
             *       "strategy": "target_vol",
             *       "estimation_window_years": 5,
             *       "vol_range": [
             *         0.02,
             *         0.2
             *       ],
             *       "drawdown_thresholds": [
             *         0.3,
             *         0.4,
             *         0.5
             *       ],
             *       "mc_paths": 10000,
             *       "seed": 42
             *     }
             */
            settings?: components["schemas"]["EngineSettings"];
        };
        /** PortfolioSummary */
        PortfolioSummary: {
            /** Expected Return */
            expected_return: number;
            /** Volatility */
            volatility: number;
            /** Target Volatility */
            target_volatility: number;
            /** Sharpe */
            sharpe: number;
            /** Beta */
            beta: number;
            /** Weighted Ter */
            weighted_ter: number;
            /** Annual Cost Per 10K */
            annual_cost_per_10k: number;
            /** Mix */
            mix: {
                [key: string]: number;
            };
        };
        /** Preferences */
        Preferences: {
            /**
             * Hedge Bonds
             * @default true
             */
            hedge_bonds?: boolean;
            /** Ucits Only */
            ucits_only?: boolean | null;
            /**
             * Regions Include
             * @default []
             */
            regions_include?: string[];
            /**
             * Regions Exclude
             * @default []
             */
            regions_exclude?: string[];
            /**
             * Sector Tilts
             * @default {}
             */
            sector_tilts?: {
                [key: string]: number;
            };
            /**
             * Sectors Exclude
             * @default []
             */
            sectors_exclude?: string[];
            /**
             * Esg Only
             * @default false
             */
            esg_only?: boolean;
            /**
             * Max Etfs
             * @default 10
             */
            max_etfs?: number;
            /**
             * Min Position
             * @default 0.03
             */
            min_position?: number;
            /**
             * Max Position
             * @default 0.4
             */
            max_position?: number;
            /** Max Ter */
            max_ter?: number | null;
            /**
             * Distribution
             * @default any
             * @enum {string}
             */
            distribution?: "acc" | "dist" | "any";
            /**
             * Crypto Max
             * @default 0
             */
            crypto_max?: number;
            /**
             * Etfs Only
             * @default false
             */
            etfs_only?: boolean;
            /** Min Fund Size Eur */
            min_fund_size_eur?: number | null;
        };
        /** PricePoint */
        PricePoint: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Value */
            value: number;
        };
        /** ProbabilityPoint */
        ProbabilityPoint: {
            /** Threshold */
            threshold: number;
            /** Probability */
            probability: number;
        };
        /** ProxiedPeriod */
        ProxiedPeriod: {
            /** Isin */
            isin: string;
            /**
             * Start
             * Format: date
             */
            start: string;
            /**
             * End
             * Format: date
             */
            end: string;
        };
        /** Question */
        Question: {
            /** Id */
            id: string;
            /** Text */
            text: string;
            /** Help */
            help?: string | null;
            /**
             * Type
             * @enum {string}
             */
            type: "single" | "number";
            /**
             * Feeds
             * @enum {string}
             */
            feeds: "capacity" | "tolerance" | "horizon";
            /**
             * Options
             * @default []
             */
            options?: components["schemas"]["QuestionOption"][];
            /** Min */
            min?: number | null;
            /** Max */
            max?: number | null;
            /** Unit */
            unit?: string | null;
        };
        /** QuestionOption */
        QuestionOption: {
            /** Label */
            label: string;
            /** Value */
            value: string;
            /**
             * Points
             * @default 0
             */
            points?: number;
        };
        /** Questionnaire */
        Questionnaire: {
            /** Version */
            version: string;
            /** Questions */
            questions: components["schemas"]["Question"][];
        };
        /** RebalanceSettings */
        RebalanceSettings: {
            /**
             * Type
             * @default none
             * @enum {string}
             */
            type?: "none" | "periodic" | "threshold";
            /**
             * Frequency
             * @default quarterly
             * @enum {string}
             */
            frequency?: "monthly" | "quarterly" | "annual";
            /**
             * Threshold
             * @default 0.05
             */
            threshold?: number;
        };
        /** Recommendation */
        Recommendation: {
            /** Holdings */
            holdings: components["schemas"]["Holding"][];
            summary: components["schemas"]["PortfolioSummary"];
            downside: components["schemas"]["Downside"];
            /**
             * Warnings
             * @default []
             */
            warnings?: string[];
            /**
             * Trace
             * @default []
             */
            trace?: components["schemas"]["StepResult"][];
        };
        /** ReferenceResult */
        ReferenceResult: {
            /** Key */
            key: string;
            /** Label */
            label: string;
            /** Isin */
            isin: string;
            /** Ticker */
            ticker: string;
            /**
             * Start
             * Format: date
             */
            start: string;
            /** Values */
            values: (number | null)[];
            /** Metrics */
            metrics: {
                [key: string]: number | null;
            };
        };
        /** StepResult */
        StepResult: {
            /** Step */
            step: string;
            /**
             * Summary
             * @default {}
             */
            summary?: {
                [key: string]: unknown;
            };
            /**
             * Notes
             * @default []
             */
            notes?: string[];
        };
        /** StressEvent */
        StressEvent: {
            /** Name */
            name: string;
            /**
             * Start
             * Format: date
             */
            start: string;
            /**
             * End
             * Format: date
             */
            end: string;
        };
        /** StressResult */
        StressResult: {
            /** Event */
            event: string;
            /**
             * Start
             * Format: date
             */
            start: string;
            /**
             * End
             * Format: date
             */
            end: string;
            /** Loss */
            loss: number | null;
            /** Proxied */
            proxied: boolean;
        };
        /** TextbookCorrelation */
        TextbookCorrelation: {
            /** Isins */
            isins: string[];
            /** Matrix */
            matrix: number[][];
        };
        /** TextbookFund */
        TextbookFund: {
            /** Isin */
            isin: string;
            /** Name */
            name: string;
            /** Ticker */
            ticker: string;
            /** Block */
            block: string;
            /** Asset Class */
            asset_class: string;
            /** Mean Return */
            mean_return: number;
            /** Volatility */
            volatility: number;
            /** Beta */
            beta: number;
            /** Capm Return */
            capm_return: number;
            /** Expected Return */
            expected_return: number;
        };
        /** TextbookInputs */
        TextbookInputs: {
            /** Window */
            window: {
                [key: string]: string;
            };
            /** Weeks */
            weeks: number;
            /**
             * Frequency
             * @default weekly
             * @constant
             */
            frequency?: "weekly";
            /** Rf */
            rf: number;
            /** Premium */
            premium: number;
            /**
             * Return Model
             * @enum {string}
             */
            return_model: "capm" | "historical";
            /** Market */
            market: {
                [key: string]: string;
            };
            /** Risk Aversion */
            risk_aversion: number;
        };
        /** TextbookMix */
        TextbookMix: {
            /** Weights */
            weights: {
                [key: string]: number;
            };
            /** Expected Return */
            expected_return: number;
            /** Volatility */
            volatility: number;
            /** Sharpe */
            sharpe: number | null;
        };
        /** TextbookPortfolio */
        TextbookPortfolio: {
            inputs: components["schemas"]["TextbookInputs"];
            /** Funds */
            funds: components["schemas"]["TextbookFund"][];
            risk_free_fund: components["schemas"]["TextbookRiskFree"];
            correlation: components["schemas"]["TextbookCorrelation"];
            /** Frontier */
            frontier: components["schemas"]["FrontierPoint"][];
            /** Capital Market Line */
            capital_market_line: components["schemas"]["FrontierPoint"][];
            tangent: components["schemas"]["TextbookMix"] | null;
            split: components["schemas"]["TextbookSplit"];
            portfolio: components["schemas"]["TextbookMix"];
            /**
             * Warnings
             * @default []
             */
            warnings?: string[];
        };
        /** TextbookRequest */
        TextbookRequest: {
            /**
             * Base Currency
             * @default EUR
             * @enum {string}
             */
            base_currency?: "EUR" | "USD";
            /**
             * Risk Level
             * @default 50
             */
            risk_level?: number;
            /**
             * Return Model
             * @default capm
             * @enum {string}
             */
            return_model?: "capm" | "historical";
            /** Market Premium */
            market_premium?: number | null;
        };
        /** TextbookRiskFree */
        TextbookRiskFree: {
            /** Isin */
            isin: string;
            /** Name */
            name: string;
            /** Ticker */
            ticker: string;
            /** Volatility */
            volatility: number;
        };
        /** TextbookSplit */
        TextbookSplit: {
            /** Risk Aversion */
            risk_aversion: number;
            /** Risky Share Uncapped */
            risky_share_uncapped: number;
            /** Risky Share */
            risky_share: number;
        };
        /**
         * UniverseFilters
         * @description The ETF universe page's filters (GET /api/universe query, POST /api/universe/frontier body).
         */
        UniverseFilters: {
            /** Asset Class */
            asset_class?: string | null;
            /** Region */
            region?: string | null;
            /** Esg */
            esg?: boolean | null;
            /** Ucits */
            ucits?: boolean | null;
            /** Max Ter */
            max_ter?: number | null;
            /** Q */
            q?: string | null;
        };
        /** UniverseFrontier */
        UniverseFrontier: {
            /** Curve */
            curve: components["schemas"]["FrontierPoint"][];
            /** Capital Market Line */
            capital_market_line: components["schemas"]["FrontierPoint"][];
            /** Points */
            points: components["schemas"]["UniversePoint"][];
            /** Rf */
            rf: number;
            /** Period */
            period: {
                [key: string]: string;
            };
            /**
             * Warnings
             * @default []
             */
            warnings?: string[];
        };
        /** UniverseFrontierRequest */
        UniverseFrontierRequest: {
            /** @default {} */
            filters?: components["schemas"]["UniverseFilters"];
            /**
             * Period Years
             * @default 5
             */
            period_years?: number;
            /**
             * Base Currency
             * @default EUR
             * @enum {string}
             */
            base_currency?: "EUR" | "USD";
            /**
             * Points
             * @default 12
             */
            points?: number;
        };
        /** UniversePoint */
        UniversePoint: {
            /** Isin */
            isin: string;
            /** Name */
            name: string;
            /** Asset Class */
            asset_class: string;
            model: components["schemas"]["FrontierPoint"];
            realised: components["schemas"]["FrontierPoint"] | null;
            /** Proxied */
            proxied: boolean;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** VarPoint */
        VarPoint: {
            /** Level */
            level: number;
            /**
             * Method
             * @enum {string}
             */
            method: "historical" | "normal";
            /** Loss */
            loss: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    defaults_api_defaults_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Defaults"];
                };
            };
        };
    };
    questionnaire_api_intake_questionnaire_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Questionnaire"];
                };
            };
        };
    };
    score_api_intake_score_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IntakeAnswers"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IntakeScore"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_funds_api_universe_get: {
        parameters: {
            query?: {
                asset_class?: string | null;
                region?: string | null;
                esg?: boolean | null;
                ucits?: boolean | null;
                max_ter?: number | null;
                /** @description case-insensitive search in name, isin, ticker, index */
                q?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FundSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    universe_frontier_api_universe_frontier_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UniverseFrontierRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UniverseFrontier"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    fund_detail_api_universe__isin__get: {
        parameters: {
            query?: {
                base_currency?: "EUR" | "USD";
            };
            header?: never;
            path: {
                isin: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FundDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    portfolio_api_portfolio_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PortfolioRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Recommendation"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    backtest_api_backtest_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BacktestRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BacktestResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    frontier_api_frontier_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FrontierRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Frontier"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    textbook_portfolio_api_textbook_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TextbookRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TextbookPortfolio"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_menu_api_menu_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Menu"];
                };
            };
        };
    };
    order_api_menu_order_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OrderRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Recommendation"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
